[package]
name = "strace-log-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Error handling
anyhow = "1"

# Command-line argument parsing
clap = "3"

# Parsing framework
nom = "7"
